### ISSUE TITLE
Unicode Full-Width Characters

### ISSUE THREAD

**Issue by forthlee** [johnnovak/illwill#35] opened 2022-09-24 14:39 UTC
Incorrect position of VertLine caused by writing Unicode Full-Width Characters
<pre>
tb.drawRect(0, 0, 40, 5)
tb.write(2, 1, fgWhite, "您好!")
┌───────────────────────────────────────┐                                                                                                                           
│ 您好!                                   │                                                                                                                           
│ Press ESC or Q to quit                │                                                                                                                           
│ ═════════════════════════════════════ │                                                                                                                           
│                                       │                                                                                                                           
└───────────────────────────────────────┘ 
</pre>

**Comment by johnnovak** [comment] 2022-11-12 22:57
Duplicate of https://github.com/johnnovak/illwill/issues/32, so closing.
Unfortunately working on illwill and adding such features to it is not one of my priorities right now.

**Closed as completed by johnnovak** 2022-11-12 22:57 UTC
